Update index.md
QuEraComputing/Bloqade.jl pull request #336
Opened 2022-05-03 20:59 UTC by minhthin1028

fix links/text

2022-05-03 21:20 UTC, Roger-luo requested changes
let's remove all the global links and replace them with markup references

2022-05-03 21:20 UTC, Roger-luo commented on docs/src/index.md
> +Currently, Bloqade enables the easy design and fast execution of quantum dynamics in the analog mode,  based on the neutral-atom quantum computing architecture. Besides fast full Hilbert-space simula
```suggestion
Currently, Bloqade enables the easy design and fast execution of quantum dynamics in the analog mode,  based on the neutral-atom quantum computing architecture. Besides fast full Hilbert-space simulation on CPUs, the main features include the design of arbitrary-layout quantum registers ([Lattices](@ref)), easy waveform generation ([Waveforms](@ref)), the simulation in subspace constrained by the Rydberg blockade ([Working with Subspace](@ref subspace)), faster GPU-accelerated simulation ([CUDA Acceleration](@ref cuda)), and more.
```

also need to add `@id cuda` in CUDA acceleration section

2022-05-03 21:31 UTC, minhthin1028 commented on docs/src/emulation.md
> +please see the [Observables](https://queracomputing.github.io/Bloqade.jl/dev/registers/) section.
Yes, all the links should be fixed as references/ids now.

2022-05-03 21:38 UTC, Roger-luo reviewed
can we double check the links locally using 

```sh
.ci/run doc serve
```

?

2022-05-03 21:38 UTC, Roger-luo commented on docs/src/emulation.md
> +please see the [Registers and Observables](@ref) section.
```suggestion
please see the [Registers and Observables](@ref observables) section.
```

2022-05-03 21:38 UTC, Roger-luo commented on docs/src/registers.md
> +refer to [Yao:Array Registers](https://docs.yaoquantum.org/dev/man/registers.html#Array-Registers) and [Yao:AbstractRegister](https://docs.yaoquantum.org/dev/man/registers.html).
```suggestion
refer to [Yao:Registers](https://docs.yaoquantum.org/dev/man/registers.html).
```

2022-05-05 21:52 UTC, Roger-luo approved these changes
LGTM

2022-05-05 21:53 UTC, merged