add lattice gauge theory example
QuEraComputing/Bloqade.jl pull request #368
Opened 2022-06-29 23:48 UTC by maolinml

We use Bloqade to reproduce the lattice gauge theory studied in this paper https://journals.aps.org/prx/pdf/10.1103/PhysRevX.10.021041. In particular, we use the feature of local detuning to create defects, from which to study the propagation of particle and antiparticle propagation, and reproduce Fig 5 of the paper. The example has been proofread, and the format has been checked with .ci/run doc serve, so should be good to go.

2022-07-01 19:49 UTC, Roger-luo requested changes

2022-07-01 19:49 UTC, Roger-luo commented on examples/6.LGT/main.jl
> +using Plots
This is not necessary

2022-07-01 19:49 UTC, Roger-luo commented on examples/6.LGT/main.jl
> +function Get_Ryd_density(Δ, Ω; dt=1e-3)
Can we follow the snake case convention? This name is also a bit confusing with the API we export (rydberg_density). A longer and more self-explainable name would be nice.

2022-07-01 19:49 UTC, Roger-luo commented on examples/6.LGT/main.jl
> +l = @layout[grid(1,2) a{0.05w}]
Maybe let's stick to matplotlib instead of Plots.jl?

2022-07-05 22:39 UTC, Roger-luo commented
@fanglifl could you help review the content? I think you are the best person to review this content. I'll help making the example run.

2022-07-05 22:53 UTC, fanglifl commented
> @fanglifl could you help review the content? I think you are the best person to review this content. I'll help making the example run.

sure, it is on my to-do list for this week! 

Thanks @maolinml, this example is really a great addition to the tutorial! I will let you know my comments soon.

2022-07-06 14:52 UTC, fanglifl approved these changes
@maolinml all look good to me! This is really a great example to add. 

Just a minor suggestion: I think there are people interested in simulating the dynamics under the pure PXP model (constrained model without the long-range interacting tails). In the current example, the dynamics is run in the subspace, while the long-range tails are still kept. 
So perhaps we could also add dynamics from pure PXP model just for educational purpose?  The building of PXP model is a little from using rydberg_h, see the last section in the subspace page: https://queracomputing.github.io/Bloqade.jl/dev/subspace/


@Roger-luo I think the wrapper function by Mao get_average_rydberg_densities could be very useful. We could perhaps consider having a similar API for general users. The input could be get_average_rydberg_densities(atoms, \omega, \delta, dt), and the output could be the time-dependent density for each site. This is essentially what we do for most of the examples:)

2022-07-07 05:29 UTC, maolinml commented
Hi @fanglifl, thanks for the suggestion. Quick question, how to create a time-varying PXP Hamiltonian? I tried the following but it does not seem to work
```
h = 2π * Omega * SumOfX(length(atoms)) - 2π * Delta * SumOfN(length(atoms))
```

2022-07-07 17:46 UTC, fanglifl commented
> Hi @fanglifl, thanks for the suggestion. Quick question, how to create a time-varying PXP Hamiltonian? I tried the following but it does not seem to work
> 
> ```
> h = 2π * Omega * SumOfX(length(atoms)) - 2π * Delta * SumOfN(length(atoms))
> ```

great question! The following expression should work: 
h = SumOfX(21, Ω) - SumOfN(21, Delta)

Btw, as we discussed on slack, the PXP model could be separated to a different example, so let us keep as it is in this tutorial. I think this current example is ready to be merged! Thanks agains @maolinml

2022-07-07 17:53 UTC, maolinml commented
Thanks @fanglifl. I will have a final edit which changes the local Rabi frequency to the local detuning fields. I will push the changes in two hours.

2022-07-07 21:02 UTC, fanglifl approved these changes
LGTM

2022-07-15 19:03 UTC, Roger-luo commented
> @Roger-luo I think the wrapper function by Mao get_average_rydberg_densities could be very useful. We could perhaps consider having a similar API for general users. The input could be get_average_rydberg_densities(atoms, \omega, \delta, dt), and the output could be the time-dependent density for each site. This is essentially what we do for most of the examples:)

@maolinml since you created the function, do you want to submit a separate PR for a high-level wrapper function for it? I can help you polish the implementation. I polish a few format issues. rest LGTM.

2022-07-15 19:06 UTC, Roger-luo approved these changes

2022-07-15 19:06 UTC, merged