Anna/test project
QuEraComputing/Bloqade.jl pull request #381
Opened 2022-07-18 16:14 UTC by Atomyka

Further unit tests for default_unit.

2022-07-18 20:53 UTC, Roger-luo commented
CI fails

2022-07-18 20:55 UTC, Roger-luo requested changes

2022-07-19 09:44 UTC, Atomyka commented on lib/BloqadeExpr/test/units.jl
> +@testset "further units" begin
Ok! I put them in the above testset since they are in the style of the previous "Hamiltonian terms"

2022-07-19 09:45 UTC, Atomyka commented
> CI fails

Ah, I think I was missing
 using BloqadeExpr: default_unit.

2022-07-19 09:47 UTC, Atomyka commented on lib/BloqadeExpr/test/units.jl
> +    @test SumOfXPhase(5, 2kHz, 2.0).ϕ ≈ 2.0 # Should test line 4, i.e. NoUnits version of default_unit
Good to know!

2022-07-19 14:42 UTC, Atomyka commented on lib/BloqadeExpr/test/units.jl
> +unitless_values = [5, 0:0.1:1, [1,2,3]]
I saw that her PR was merged into the master branch, so I thought I should build on top of that?
Or is that something you would take care of as the administrator?

2022-07-19 14:42 UTC, Atomyka commented on lib/BloqadeExpr/test/units.jl
> +unitless_values = [5, 0:0.1:1, [1,2,3]]
I saw that her PR was merged into the master branch, so I thought I should build on top of that?
Or is that something you would take care of as the administrator?

2022-07-19 15:25 UTC, Roger-luo commented
close in favor of #381

2022-07-19 15:25 UTC, closed without merging