Weinbe58/descretize waveform
QuEraComputing/Bloqade.jl pull request #394
Opened 2022-08-22 19:00 UTC by weinbe58

new code to convert arbitrary waveforms into piecewise linear given constraints and tolerances. 

This will be used in the BloqadeSchema to port protocols to JSON files.

2022-08-22 19:11 UTC, Roger-luo requested changes

2022-08-22 19:11 UTC, Roger-luo commented on lib/BloqadeWaveforms/src/descretize.jl
> +    for i in 1:length(c)-1
```suggestion
    @inbounds for i in 1:length(c)-1
```

2022-08-22 19:11 UTC, Roger-luo commented on lib/BloqadeWaveforms/src/descretize.jl
> +    stack = Tuple{Float64,Float64}[(0.0,wf.duration)]
```suggestion
    stack = [(0.0,wf.duration)]
```

2022-08-22 19:11 UTC, Roger-luo commented on lib/BloqadeWaveforms/src/descretize.jl
> +    intervals = Tuple{Float64,Float64,Float64,Float64}[]
```suggestion
    intervals = NTuple{4, T}[]
```

2022-08-22 19:11 UTC, Roger-luo commented on lib/BloqadeWaveforms/src/descretize.jl
> +function descretize_waveform(wf::Waveform;
```suggestion
function descretize_waveform(wf::Waveform{F, T}; 
```

2022-08-22 19:11 UTC, Roger-luo commented on lib/BloqadeWaveforms/src/descretize.jl
> +    tol::Float64 = 1.0e-5)
```suggestion
    tol::Float64 = 1.0e-5) where {T}
```

2022-08-22 19:11 UTC, Roger-luo commented on lib/BloqadeWaveforms/src/descretize.jl
> +
```julia
T = promote_type(T, Float64)
```

2022-08-22 19:11 UTC, Roger-luo commented on lib/BloqadeWaveforms/test/descretize.jl
> +    try
use `@test_throws`

2022-08-23 04:25 UTC, Roger-luo commented
Need to merge master to get tests pass

2022-08-23 17:53 UTC, Roger-luo approved these changes
LGTM

2022-08-23 19:29 UTC, weinbe58 commented
What does that mean?

2022-08-23 20:28 UTC, Roger-luo commented
sry, it means "looks good to me" (Damn it feels good that I'm not the only one keep checking the urban dictionary :P ). 

So we usually follow the [colprac](https://github.com/SciML/ColPrac) workflow in general, so if you have merge rights and your PR passed review, you should merge it by yourself (since sometimes people may change their mind and want to further modify their own PR)

2022-08-23 20:55 UTC, weinbe58 commented
I will add documentation for this function then merge the PR.

2022-08-24 13:33 UTC, merged