Added ability to submit Bloqade Hamiltonians to Braket
QuEraComputing/Bloqade.jl pull request #485
Opened 2022-12-06 17:53 UTC by johnzl-777

Allow conversion from `TaskSpecification` to the Braket IR as well as submitting Hamiltonians to Braket.

2022-12-06 23:02 UTC, weinbe58 requested changes
Over all looks good one thing we should try to think about is how to test the submission to braket maybe we can rope in someone as aws.

2022-12-06 23:02 UTC, weinbe58 commented on lib/BloqadeSchema/src/submit_to_braket.jl
> +using AWS
Move these "using" statements to BloqadeSchema.jl

2022-12-06 23:02 UTC, weinbe58 commented on lib/BloqadeSchema/src/to_braket_ahs_ir.jl
> +using DecFP
Same as above

2022-12-07 14:41 UTC, johnzl-777 commented
> Over all looks good one thing we should try to think about is how to test the submission to braket maybe we can rope in someone as aws.

Is this a blocker for getting this PR merged?

2022-12-07 16:01 UTC, weinbe58 commented
> > Over all looks good one thing we should try to think about is how to test the submission to braket maybe we can rope in someone as aws.
> 
> Is this a blocker for getting this PR merged?

No, we know it works we just don't have test coverage.

2022-12-07 16:04 UTC, weinbe58 approved these changes
After these changes you can merge.

2022-12-07 16:04 UTC, weinbe58 commented on lib/BloqadeSchema/src/submit_to_braket.jl
> +`nothing`, in which case credentials will be sought after in the shell environment variables.
```suggestion
`nothing`, in which case credentials will be sought in the standard AWS locations. 
```

2022-12-07 16:04 UTC, weinbe58 commented on lib/BloqadeSchema/src/submit_to_braket.jl
> +`nothing`, in which case credentials will be sought after in the shell environment variables.
```suggestion
`nothing`, in which case credentials will be sought in the standard AWS locations. 
```

2022-12-07 16:04 UTC, weinbe58 commented on lib/BloqadeSchema/src/submit_to_braket.jl
> +`nothing`, in which case credentials will be sought after in the shell environment variables.
```suggestion
`nothing`, in which case credentials will be sought in the standard AWS locations. 
```

2022-12-07 16:11 UTC, merged