Plot Rydberg Densities & Calculate from `AnalogHamiltonianSimulationTaskResult`
QuEraComputing/Bloqade.jl pull request #539
Opened 2023-03-17 18:47 UTC by johnzl-777

Added `plot_densities` function that plots the Rydberg densities for each site over the atom positions. Also added new definition for `rydberg_density` to calculate densities from a Braket.jl `AnalogHamiltonianTaskResult`.

2023-03-17 20:12 UTC, johnzl-777 commented on src/Bloqade.jl
> +using Braket: AnalogHamiltonianSimulationQuantumTaskResult
I figured it was 🐟 😅 , I'll give putting it into an extension a shot!

2023-03-21 14:51 UTC, johnzl-777 commented
Instead of the Package extensions and after talking more with @weinbe58 I've opted to do the following to minimize the number of new dependencies Bloqade has to handle and disturbing the existing API.

Considering `BloqadeSchema` is the main library for interacting with quantum hardware through `Bloqade` AND it already depends on `Braket.jl`:
* `rydberg_density` for `AnalogHamiltonianSimulationQuantumTaskResult` now lives in `BloqadeSchema` (it is not exported to avoid conflict with `rydberg_density` in base `Bloqade`)
* `plot_densities` has been generalized (it will just accept a vector of Rydberg densities versus having two definitions for two separate types), removing the direct dependence on `Braket.jl` and living in `plots.jl`.

The only additional cost is that Bloqade is now dependent on `Colors.jl` and `ColorSchemes.jl`.

2023-03-21 19:23 UTC, weinbe58 requested changes

2023-03-21 19:23 UTC, weinbe58 commented on test/plots.jl
> +@testset "plot_densities" begin
can we also add a test that doesn't throw an error to make sure we cover that branch?

2023-03-21 20:32 UTC, weinbe58 approved these changes
LGTM

2023-03-21 20:33 UTC, merged